from enum import StrEnum


class ProcessingState(StrEnum):
    PENDING = "PENDING"
    DOWNLOADED = "DOWNLOADED"
    RAW_STORED = "RAW_STORED"
    CANONICALIZED = "CANONICALIZED"
    CHUNKED = "CHUNKED"
    EMBEDDED = "EMBEDDED"
    EXTRACTED = "EXTRACTED"
    EXPORTED = "EXPORTED"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    ABSTAINED = "ABSTAINED"
    SKIPPED = "SKIPPED"
